<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Fiap.TechChallenge.OficinaMecanica.Api</RootNamespace>
    <AssemblyName>Fiap.TechChallenge.OficinaMecanica.Api</AssemblyName>
    <UserSecretsId>44582d86-54cc-4659-bc1a-a14dc112a037</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql" Version="10.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <Content Remove="tests\**\*" />
    <EmbeddedResource Remove="tests\**\*" />
    <None Remove="tests\**\*" />
    <Compile Remove="Fiap.TechChallenge.OficinaMecanica.Test.IntegrationTests\**\*.cs" />
    <Content Remove="Fiap.TechChallenge.OficinaMecanica.Test.IntegrationTests\**\*" />
    <EmbeddedResource Remove="Fiap.TechChallenge.OficinaMecanica.Test.IntegrationTests\**\*" />
    <None Remove="Fiap.TechChallenge.OficinaMecanica.Test.IntegrationTests\**\*" />
    <Compile Remove="Fiap.TechChallenge.OficinaMecanica.Test.UnitTests\**\*.cs" />
    <Content Remove="Fiap.TechChallenge.OficinaMecanica.Test.UnitTests\**\*" />
    <EmbeddedResource Remove="Fiap.TechChallenge.OficinaMecanica.Test.UnitTests\**\*" />
    <None Remove="Fiap.TechChallenge.OficinaMecanica.Test.UnitTests\**\*" />
  </ItemGroup>

</Project>
