apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  Jwt__Issuer: "Fiap.TechChallenge.OficinaMecanica"
  Jwt__Audience: "Fiap.TechChallenge.OficinaMecanica"
  Jwt__ExpirationMinutes: "60"
