# Mude para sua senha e nunca suba em um commit
# Em producao deve criar o secret diretamente no cluster ou usar um gerenciador externo
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: oficina-mecanica
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "suasenha"
