name: Feature / Hotfix CI

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'

permissions:
  contents: read
  packages: write  

jobs:
  build-and-test:
    name: Build and Tests
    uses: ./.github/workflows/_reusable-build-test.yml
    with:
      run-integration-tests: true

  terraform-validate:
    name: Terraform Validate
    uses: ./.github/workflows/_reusable-terraform-validate.yml
    with:
      create-pr: false

